lamby/controllers/models.py
import datetime as dt

import requests
from flask import Blueprint, flash, jsonify, redirect, render_template, url_for
from flask_login import current_user, login_required

from lamby.api.deploy import create_droplet, delete_droplet
from lamby.database import db
from lamby.filestore import fs
from lamby.models.commit import Commit
from lamby.models.deployment import Deployment
from lamby.models.meta import Meta
from lamby.models.project import Project

models_blueprint = Blueprint('models', __name__)


@models_blueprint.route('/<string:project_id>/<string:commit_id>')
def model(project_id, commit_id):
    project = Project.query.get(project_id)

    if project is None:
        flash('That project does not exist!', category='danger')
        return redirect(url_for('projects.index'))

    project = Project.query.get(project_id)
    commit = Commit.query.get(commit_id)
    author = project.owner.email
    timestamp = dt.datetime.utcfromtimestamp(
        commit.timestamp).strftime('%m-%d-%Y %I:%M %p')

    message = commit.message

    if commit is None:
        flash('That commit does not exist!', category='danger')
        return redirect(url_for('projects.index'))

    meta = Meta.query.filter_by(
        project_id=project_id,
        filename=commit.filename
    ).first()

    context = {
        'project': project,
        'commit_id': commit_id,
        'author': author,
        'timestamp': timestamp,
        'message': message,
        'commits': Commit.query.filter_by(
            project_id=project.id,
            filename=commit.filename

        ),
        'head': meta.head,
        'object_link': fs.get_link(project_id, commit_id),
        'is_deployed': Deployment.is_deployed(project_id, commit_id)
    }

    return render_template('netron.jinja', **context)


@models_blueprint.route('/change_head/<int:project_id>/<string:commit_id>',
                        methods=['POST'])
@login_required
def change_head(project_id, commit_id):
    project = Project.query.get(project_id)

    if project is None:
        flash('No such project!', category='danger')
        return jsonify({'message': 'invalid project'})

    commit = Commit.query.get(commit_id)

    if commit is None:
        flash('There was an error changing the head commit', category='danger')
        return jsonify({'message': 'invalid commit'}), 400

    meta = Meta.query.filter_by(
        project_id=project_id,
        filename=commit.filename
    ).first()

    meta.head = commit.id

    try:
        db.session.commit()
        flash(
            'You have successfully changed the head',
            category='success'
        )
    except Exception as e:
        flash('There was an error:', e)
        return jsonify({'message': 'unknown error'}), 400

    return jsonify({'message': 'success'}), 200


@models_blueprint.route('/deploy/<int:project_id>/<string:commit_id>',
                        methods=['POST'])
@login_required
def deploy_model(project_id, commit_id):
    project = Project.query.get(project_id)

    if current_user.id != project.owner_id:
        flash('Invalid user credential privilege! Unable to deploy.',
              category='danger')
        return jsonify({'message': 'invalid user'})

    if project is None:
        flash('No such project!', category='danger')
        return jsonify({'message': 'invalid project'})

    commit = Commit.query.get(commit_id)

    if commit is None:
        flash('There was an error changing the head commit', category='danger')
        return jsonify({'message': 'invalid commit'}), 400

    deploy = Deployment.query.filter_by(
        project_id=project_id,
        commit_id=commit_id
    ).first()

    if deploy is not None:
        flash('That commit is already deployed!', category='danger')
        return jsonify({'message': 'already deployed'})

    # create droplet and deploy here
    deployment_ip = ''
    droplet_id = ''
    try:
        droplet_id, deployment_ip = create_droplet(
            f'{project.id}-{commit.filename}-{commit.id[0:7]}'[0:63],
            fs.get_link(project_id, commit_id),
            commit_id
        )
    except requests.exceptions.Timeout:
        return jsonify({'message': 'Droplet creation timed out.'})
    except requests.exceptions.RequestException:
        return jsonify({'message': 'Droplet creation error.'})

    # TODO: remove hardcoded ip
    deploy = Deployment(
        project_id=project_id,
        commit_id=commit_id,
        deployment_ip=deployment_ip,
        droplet_id=int(droplet_id)
    )

    db.session.add(deploy)
    db.session.commit()

    flash('Deployed Model!', category='success')
    return jsonify({'message': 'Success'})


@models_blueprint.route('/undeploy/<int:project_id>/<string:commit_id>',
                        methods=['POST'])
@login_required
def undeploy_model(project_id, commit_id):
    project = Project.query.get(project_id)

    if project is None:
        flash('No such project!', category='danger')
        return jsonify({'message': 'invalid project'}), 404

    if current_user.id != project.owner_id:
        flash(
            'Only the project owner can perform that action!',
            category='danger'
        )
        return jsonify({'message': 'invalid user'}), 401

    commit = Commit.query.get(commit_id)

    if commit is None:
        flash('This commit doesn\'t exist!', category='danger')
        return jsonify({'message': 'invalid commit'}), 400

    deploy = Deployment.query.filter_by(
        project_id=project_id,
        commit_id=commit_id
    ).first()

    if deploy is None:
        flash('That commit is not currently deployed!', category='danger')
        return jsonify({'message': 'not deployed'})

    try:
        delete_droplet(deploy.droplet_id)
    except requests.exceptions.Timeout:
        return jsonify({'message': 'Droplet delete timed out.'})
    except requests.exceptions.RequestException:
        return jsonify({'message': 'Droplet delete error.'})

    db.session.delete(deploy)
    db.session.commit()

    flash('Deleted deployment!', category='success')
    return jsonify({'message': 'success'})

lamby/api/auth.py
from flask import Blueprint, jsonify, request

from lamby.database import db
from lamby.models.user import User

auth_api_blueprint = Blueprint('auth_api', __name__)


@auth_api_blueprint.route('/token', methods=['POST'])
def get_api_token():
    data = request.get_json()
    user = User.query.filter_by(email=data['email']).first()

    response = {}

    if user is None or not user.check_password(data['password']):
        response['message'] = 'Invalid credentials!'
        return jsonify(response), 401

    if user.api_key is None:
        user.generate_new_api_key()
        db.session.commit()

    response['message'] = 'Successfully fetched API key!'
    response['api_key'] = user.api_key

    return jsonify(response), 200

lamby/controllers/deploy.py
import os

from flask import Blueprint, abort, render_template

from lamby.filestore import fs
from lamby.models.commit import Commit

deploy_blueprint = Blueprint('deploy', __name__)


@deploy_blueprint.route('/<commit_id>')
def deploy(commit_id):
    commit = Commit.query.get(commit_id)

    if commit is None:
        abort(404)

    return render_template(
        'deploy.jinja',
        commit=commit,
        token=os.getenv('DIGITAL_OCEAN_API_KEY'),
        link=fs.get_link(f'{commit.project_id}/{commit.id}')
    )

lamby/controllers/profile.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from lamby.database import db
from lamby.forms.profile import (DeleteAccountForm, MyApiKeyForm, MyInfoForm,
                                 NewProjectForm)
from lamby.models.commit import Commit
from lamby.models.project import Project
from lamby.models.user import User

profile_blueprint = Blueprint('profile', __name__)


@profile_blueprint.route('/')
@login_required
def index():
    context = {
        'owner': current_user,
        'my_info_form': MyInfoForm(),
        'my_api_key_form': MyApiKeyForm(),
        'delete_account_form': DeleteAccountForm(),
        'new_project_form': NewProjectForm(),
        'focused_tab': 'projects'
    }

    return render_template('profile.jinja', **context)


@profile_blueprint.route('/my_info', methods=['POST'])
@login_required
def handle_my_info_form():
    my_info_form = MyInfoForm()

    if my_info_form.validate_on_submit():
        current_user.set_password(my_info_form.new_password.data)
        db.session.commit()
        flash('The change to your account was successful.', category='success')
        return redirect(url_for('profile.index'))

    context = {
        'owner': current_user,
        'my_info_form': MyInfoForm(),
        'my_api_key_form': MyApiKeyForm(),
        'delete_account_form': DeleteAccountForm(),
        'new_project_form': NewProjectForm(),
        'focused_tab': 'info'
    }

    return render_template('profile.jinja', **context)


@profile_blueprint.route('/my_api_key', methods=['POST'])
@login_required
def handle_my_api_key_form():
    my_api_key_form = MyApiKeyForm()

    if my_api_key_form.validate_on_submit():
        current_user.generate_new_api_key()
        db.session.commit()
        flash('A new API Key has been generated.', category='success')
        return redirect(url_for('profile.index'))

    # Attempted to generate a new api key, but something went wrong
    flash('Something went wrong! Please try again later.', category='danger')
    return redirect(url_for('profile.index'))


@profile_blueprint.route('/delete_account', methods=['POST'])
@login_required
def handle_delete_account():
    delete_account_form = DeleteAccountForm()

    if delete_account_form.validate_on_submit():
        user = User.query.filter(User.id == current_user.id).one()

        for p in Project.query.filter(Project.owner_id == current_user.id):
            for c in Commit.query.filter(Commit.project_id == p.id):
                db.session.delete(c)

        db.session.delete(user)
        db.session.commit()

        flash(
            'You have successfully deleted your account!',
            category='success'
        )
        return redirect(url_for('auth.login'))

    # Attempted to generate a new api key, but something went wrong
    flash('Something went wrong! Please try again later.', category='danger')
    return redirect(url_for('profile.index'))


@profile_blueprint.route('/new_project', methods=['POST'])
@login_required
def create_new_project():
    new_project_form = NewProjectForm()

    if new_project_form.validate_on_submit():
        project = Project(title=new_project_form.project_title.data,
                          description=new_project_form.project_desc.data,
                          owner_id=current_user.id)
        current_user.projects.append(project)

        db.session.add(project)
        db.session.commit()

        flash('You have successfully created a new project!',
              category='success')
        return redirect(url_for('profile.index'))

    # Attempted to generate a new api key, but something went wrong
    flash('Something went wrong! Please try again later.', category='danger')
    return redirect(url_for('profile.index'))

lamby/controllers/projects.py
import time

import mistune
from flask import Blueprint, abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from lamby.database import db
from lamby.filestore import fs
from lamby.forms.projects import (DeleteProjectForm, EditMembersForm,
                                  EditReadmeForm)
from lamby.models.commit_attr import CommitAttr
from lamby.models.deployment import Deployment
from lamby.models.meta import Meta
from lamby.models.project import Project
from lamby.models.user import User

projects_blueprint = Blueprint('projects', __name__)


@projects_blueprint.route('/')
def index():
    projects = Project.query.limit(10).all()
    return render_template('projects.jinja', projects=projects)


@projects_blueprint.route('/<int:project_id>')
def project(project_id):
    project = Project.query.get(project_id)

    if project is None:
        abort(404)

    model_table_data = [{
        'filename': commit.filename,
        'message': commit.message,
        'link': f'/models/{project.id}/{commit.id}',
        'commit_id': commit.id,
        'is_deployed': Deployment.is_deployed(project_id, commit.id),
        'timestamp': time.strftime(
            '%Y-%m-%d',
            time.localtime(commit.timestamp)
        )
    } for commit in Meta.get_latest_commits(project.id)]

    markdown = mistune.Markdown()
    member_emails = '\n'.join([member.email for member in project.members])

    context = {
        'project': project,
        'model_table_data': model_table_data,
        'formatted_readme': markdown(project.readme),
        'edit_readme_form': EditReadmeForm(markdown=u'' + project.readme),
        'delete_project_form': DeleteProjectForm(),
        'edit_members_form': EditMembersForm(members=member_emails),
        'formatted_date_created': time.strftime(
            '%Y-%m-%d',
            time.localtime(project.date_created)
        )
    }

    return render_template('project.jinja', **context)


@projects_blueprint.route('/readme/<int:project_id>', methods=['POST'])
@login_required
def handle_edit_readme(project_id):
    edit_readme_form = EditReadmeForm()

    project = Project.query.get(project_id)

    if project is None:
        flash('No such project!', category='danger')
        return redirect(url_for('profile.index'))

    if current_user.id != project.owner_id:
        flash(
            'You do not have permission to edit this README!',
            category='danger'
        )
        return redirect(url_for('profile.index'))

    if edit_readme_form.validate_on_submit():
        project = Project.query.get(project_id)
        project.readme = edit_readme_form.markdown.data

        db.session.commit()

        flash('Successfully updated README.', category='success')
        return redirect(url_for('projects.project', project_id=project_id))

    flash('Unable to update README.', category='failure')
    return redirect(url_for('projects.project', project_id=project_id))


@projects_blueprint.route('/delete/<int:project_id>', methods=['POST'])
@login_required
def handle_delete_project(project_id):
    delete_project_form = DeleteProjectForm()

    if delete_project_form.validate_on_submit():
        project = Project.query.get(project_id)

        if project is None:
            flash('No such project!', category='danger')
            return redirect(url_for('profile.index'))

        if current_user.id != project.owner_id:
            flash(
                'You do not have permission to delete this project!',
                category='danger'
            )
            return redirect(url_for('profile.index'))

        # Remove project from minio
        fs.delete_project(project)

        # Clean up data in the Meta table
        for meta in Meta.query.filter_by(project_id=project_id):
            db.session.delete(meta)

        # Clean up data in the Commit table
        for commit in project.commits:
            # Clean up data in the CommitAttr table
            for attr in CommitAttr.query.filter_by(commit_id=commit.id):
                db.session.delete(attr)
            db.session.delete(commit)

        # Remove the project from each of the members' projects
        for member in project.members:
            member.projects.remove(project)

        # Remove project from the user's owned projects
        current_user.owned_projects.remove(project)

        db.session.delete(project)
        db.session.commit()

        flash('You have successfully delete the project!', category='success')
        return redirect(url_for('profile.index'))

    flash('Something went wrong! Please try again later.', category='danger')
    return redirect(url_for('profile.index'))


@projects_blueprint.route('/edit_members/<int:project_id>', methods=['POST'])
@login_required
def handle_members(project_id):
    edit_members_form = EditMembersForm()

    # When Save Changes button is clicked
    if edit_members_form.validate_on_submit():
        project = Project.query.get(project_id)

        if project is None:
            flash('No such project!', category='danger')
            return redirect(url_for('profile.index'))

        if current_user not in project.members:
            flash(
                'You do not have permission to add members to this project!',
                category='danger'
            )
            return redirect(url_for('projects.project', project_id=project_id))

        member_emails = edit_members_form.members.data.split('\n')

        for email in member_emails:
            user = User.query.filter_by(email=email.strip()).first()

            if user is None:
                flash(
                    f'Cannot find user with email: {email}',
                    category='danger'
                )
                return redirect(url_for('projects.project',
                                        project_id=project_id))

            if user not in project.members:
                project.members.append(user)
        try:
            db.session.commit()
            flash(
                f'Successfully updated members for {project.title}',
                category='success'
            )
            return redirect(url_for('projects.project',
                                    project_id=project_id))
        except Exception as e:
            flash(
                f'Error updating members for {project.title}:  {e}',
                category='danger'
            )
            return redirect(url_for('projects.project',
                                    project_id=project_id))

lamby/templates/deploy.jinja
{% extends 'helpers/base.jinja' %}

{% block title %}Deploy{% endblock %}

{% block content %}

<script src="{{ url_for('static', filename='js/deploy.js') }}"></script>
<script type="text/javascript">
  createDroplet('{{ token }}', '{{ commit.project_id }}', '{{ commit.id }}', '{{ link }}');
</script>

{% endblock %}

lamby/templates/netron.jinja
{% extends "helpers/base.jinja" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='netron/open-sans.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='netron/view-grapher.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='netron/view-sidebar.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='netron/view.css') }}">
{% endblock %}

{% block title %}Model{% endblock %}

{% block meta %}
<meta name='type' content='Python' />
<meta name='file' content='{{ object_link }}' />
{% endblock %}

{% block content %}

{# Commit Metadata #}
<div class="uk-subnav uk-subnav-divider">
    <span>
        <li class="uk-button uk-button-default" type="button">Commits <span uk-icon="icon:  triangle-down"></span></li>
        {% if current_user in project.members %}
            <li class="uk-button uk-button-default" type="button" onclick="changeHead()">Change Head</li>
        {% endif %}

        {% if current_user.id == project.owner_id %}
            <li
                class="uk-button uk-button-default"
                type="button"
                onclick="{% if is_deployed %}deleteDeployment(){% else %}deployModel(){% endif %}"
            >
                {% if is_deployed %} UNDEPLOY {% else %} DEPLOY {% endif %}
            </li>
        {% endif %}
    </span>
    <li class="">Current Commit: {{ commit_id|truncate(7, True, '') }}</li>
    <li class="">Author: {{ author }}</li>
    <li class="">Timestamp: {{ timestamp }}</li>
    <li class="">Message: {{ message }}</li>
</div>

{# Commits Drop Down Information #}
<div uk-dropdown="mode: click;">
    <ul class="uk-nav uk-dropdown-nav">
    {% for commit in commits %}
        <li>
            <a href="/models/{{ project.id }}/{{ commit.id }}">
                {% if commit.id == head %}<b>HEAD:</b>{% endif %}
                {{ commit.id|truncate(7, True, '') }}
            </a>
        </li>
    {% endfor %}
    </ul>
</div>
<br />

<script type="text/javascript">
    const changeHead = async () => {
        try {
            const endpoint = "{{ url_for('models.change_head', project_id=project.id, commit_id=commit_id) }}";
            const res = await fetch(endpoint, {
                method: "POST",
                body: {},
            });
            window.location.href = "{{ request.url }}";
        } catch (err) {
            window.location.href = "{{ request.url }}";
        }
    }

    const deployModel = async () => {
        const endpoint = "{{ url_for('models.deploy_model', project_id=project.id, commit_id=commit_id) }}";
        const res = await fetch(endpoint, {
            method: "POST",
            body: {}
        });
        window.location.href = "{{ request.url }}";
    }

    const deleteDeployment = async () => {
        const endpoint = "{{ url_for('models.undeploy_model', project_id=project.id, commit_id=commit_id) }}";
        const res = await fetch(endpoint, {
            method: "POST",
            body: {}
        });
        window.location.href = "{{ request.url }}";
    }
</script>

<a class="center logo" href="https://github.com/lutzroeder/netron" target="_blank">
    <svg id="spinner" class="spinner logo absolute" viewbox="0 0 1024 1024" style="display: none;">
        <g transform="translate(512, 512)" style="opacity: 1">
            <path class="stroke" d="M-431,0 A-431,-431 0 0,1 0,-431" stroke-width="24" fill="None"></path>
        </g>
    </svg>
</a>

<div id="graph-container" style="overflow: scroll; width: 100%; height: 100%">
    <svg id="graph" class="graph" preserveaspectratio="xMidYMid meet" width="100%" height="100%"></svg>
</div>

<div id="toolbar" class="toolbar" style="position: absolute; top: 50px; display: none;">
    <button id="model-properties-button" title="Model Properties">
        <svg class="icon" viewbox="0 0 100 100">
            <rect class="border" x="12" y="12" width="76" height="76" rx="16" ry="16" stroke-width="8"></rect>
            <line class="border" x1="30" y1="37" x2="70" y2="37" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <line class="border" x1="30" y1="50" x2="70" y2="50" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <line class="border" x1="30" y1="63" x2="70" y2="63" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <rect class="stroke" x="12" y="12" width="76" height="76" rx="16" ry="16" stroke-width="4"></rect>
            <line class="stroke" x1="30" y1="37" x2="70" y2="37" stroke-width="4" stroke-linecap="round"></line>
            <line class="stroke" x1="30" y1="50" x2="70" y2="50" stroke-width="4" stroke-linecap="round"></line>
            <line class="stroke" x1="30" y1="63" x2="70" y2="63" stroke-width="4" stroke-linecap="round"></line>
        </svg>
    </button>
    <button id="zoom-in-button" title="Zoom In">
        <svg class="icon" viewbox="0 0 100 100">
            <circle class="border" cx="50" cy="50" r="35" stroke-width="8" stroke="#fff"></circle>
            <line class="border" x1="50" y1="38" x2="50" y2="62" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <line class="border" x1="38" y1="50" x2="62" y2="50" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <line class="border" x1="78" y1="78" x2="82" y2="82" stroke-width="12" stroke-linecap="square" stroke="#fff"></line>
            <circle class="stroke" cx="50" cy="50" r="35" stroke-width="4"></circle>
            <line class="stroke" x1="50" y1="38" x2="50" y2="62" stroke-width="4" stroke-linecap="round"></line>
            <line class="stroke" x1="38" y1="50" x2="62" y2="50" stroke-width="4" stroke-linecap="round"></line>
            <line class="stroke" x1="78" y1="78" x2="82" y2="82" stroke-width="8" stroke-linecap="square"></line>
        </svg>
    </button>
    <button id="zoom-out-button" title="Zoom Out">
        <svg class="icon" viewbox="0 0 100 100">
            <circle class="border" cx="50" cy="50" r="35" stroke-width="8" stroke="#fff"></circle>
            <line class="border" x1="38" y1="50" x2="62" y2="50" stroke-width="8" stroke-linecap="round" stroke="#fff"></line>
            <line class="border" x1="78" y1="78" x2="82" y2="82" stroke-width="12" stroke-linecap="square" stroke="#fff"></line>
            <circle class="stroke" cx="50" cy="50" r="35" stroke-width="4"></circle>
            <line class="stroke" x1="38" y1="50" x2="62" y2="50" stroke-width="4" stroke-linecap="round"></line>
            <line class="stroke" x1="78" y1="78" x2="82" y2="82" stroke-width="8" stroke-linecap="square"></line>
        </svg>
    </button>
</div>

<div id="sidebar" class="sidebar">
    <h1 id="sidebar-title" class="sidebar-title"></h1>
    <a href="javascript:void(0)" id="sidebar-closebutton" class="sidebar-closebutton">&times;</a>
    <div id="sidebar-content" class="sidebar-content">
    </div>
</div>

{# Netron JS requirements #}
<script type="text/javascript" src="{{ url_for('static', filename='netron/d3.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/dagre.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/protobuf.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/flatbuffers.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/handlebars.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/marked.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/pako.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/long.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/base.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/zip.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/gzip.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/tar.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/view-grapher.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/view-sidebar.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/view.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='netron/view-browser.js') }}"></script>

{% endblock %}

lamby/templates/profile.jinja
{% extends "helpers/base.jinja" %}

{% from 'macros/projects.jinja' import render_projects with context %}
{% from 'macros/deployments.jinja' import render_deployments with context %}

{% block title %}Profile{% endblock %}

{% block content %}

<h2 class="uk-text-center">
  {% if owner == current_user %}
    Profile
  {% else %}
    {{ owner.email }}'s Projects
  {% endif %}
</h2>

{% if owner == current_user %}
  <ul class="uk-tab" uk-switcher>
      {% if focused_tab == 'projects' %}
          <li class="uk-active"><a href="#">Projects</a></li>
          <li><a href="#">Deployments</a></li>
          <li><a href="#">My Info</a></li>
      {% else %}
          <li><a href="#">Projects</a></li>
          <li class="uk-active"><a href="#">My Info</a></li>
      {% endif %}
  </ul>

  <ul class="uk-switcher uk-margin">
      {# Projects Tab #}
      <li>
          {# Display projects grid #}
          {{ render_projects(current_user.projects) }}

          {# New project button #}
          <div class="uk-position-bottom-right" style="margin-right:50px; margin-bottom:50px">
              <button class="uk-button uk-button-default uk-button-large" type="button" uk-toggle="target: #new-project-modal">New Project</button>
          </div>

          {# New Project Modal #}
          <div id="new-project-modal" uk-modal>
              <div class="uk-modal-dialog uk-modal-body">
                  <h2 class="uk-modal-title">New Project</h2>
                  <form method="post" action="{{ url_for('profile.create_new_project') }}" novalidate>
                      {{ new_project_form.hidden_tag() }}
                      {{ new_project_form.project_title(class_="uk-input uk-align", type="text", placeholder="Project Name") }}
                      {{ new_project_form.project_desc(class_="uk-input uk-align", type="text", placeholder="Project Description") }}
                      <p class="uk-text-right">
                          {{ new_project_form.submit(class_="uk-button uk-button-primary uk-width-1-2 uk-margin-small-bottom uk-align") }}
                      </p>
                  </form>
              </div>
          </div>
      </li>

      {# Deployments Tab #}
      <li>
        {% for project in current_user.owned_projects %}
            <h4 class="uk-text-center">{{ project.title }}'s Deployed Models</h4>
            {{ render_deployments(project.deployments) }}
        {% endfor %}
      </li>

      {# My Info Tab #}
      <li>
          <ul>
              <div class="uk-child-width-expand@s uk-text-center" uk-grid>
                  <div>
                      <form method="post" action="{{ url_for('profile.handle_my_info_form') }}" novalidate>
                          {{ my_info_form.hidden_tag() }}

                          <div align="left">
                              <h4>Email</h4>
                              {{ my_info_form.email(class_="uk-input uk-align", type="text", value=current_user.email, disabled=true) }}

                              <h4>Change Password</h4>
                              {{ my_info_form.old_password(class_="uk-input uk-align", type="password", placeholder="Old Password") }}
                              {{ my_info_form.new_password(class_="uk-input uk-align", type="password", placeholder="New Password") }}
                              {{ my_info_form.submit(class_="uk-button uk-button-primary uk-width-1-2 uk-margin-small-bottom uk-align") }}
                          </div>
                      </form>
                      <form method="post" action="{{ url_for('profile.handle_delete_account') }}" novalidate>
                          {{ delete_account_form.hidden_tag() }}

                          <div align="left">
                              <h4></h4>
                              <h4>Delete Account</h4>
                              {{ delete_account_form.submit(class_="uk-button uk-button-danger uk-width-1-2 uk-margin-small-bottom uk-align") }}
                          </div>
                      </form>
                  </div>

                  <div>
                      <form method="post" action="{{ url_for('profile.handle_my_api_key_form') }}" novalidate>
                          {{ my_api_key_form.hidden_tag() }}

                          <div align="left">
                              <h4>API Key</h4>
                              {{ my_api_key_form.api_key(class_="uk-input uk-align", type="text", value=(current_user.api_key or 'NULL'), disabled=true) }}
                              {{ my_api_key_form.generate_new_key(class_="uk-button uk-button-primary uk-width-1-2 uk-margin-small-bottom uk-align") }}
                          </div>
                      </form>
                  </div>
              </div>
          </ul>
      </li>
  </ul>
{% else %}
  {{ render_projects(owner.projects) }}
{% endif %}

{% endblock %}